keys:
  - &adrian age1xh4n72js0mxclzxswgwnegh5dxl96ejj4l2j05m654j4x0yx7qlsfgldlz 
  - &desktop age1695v27tjvh2wkdwhge4t38mg2m8pasw7dyfxnmymc5gcfjsnkv3snp7h08
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *adrian
        - *desktop
