# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  # boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/bf9a3be8-df46-4101-843b-4f516a5a8e6a";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fea80a9c-b964-4b58-a379-641903a79041";
      fsType = "ext4";
    };

  fileSystems."/mnt/ssd" =
    { device = "/dev/disk/by-uuid/f341c079-e2c6-4238-95af-02f593739df8";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1835-560A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/adrian/.local/share/docker/volumes" =
    { device = "/mnt/ssd/docker-volumes";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/adrian/ssd-repos" =
    { device = "/mnt/ssd/repos";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/mnt/ssd/docker";
      fsType = "none";
      options = [ "bind" ];
    };

  # zdata pools have been created following approaches outlined in:
  # https://www.return12.net/zfs-on-nixos/
  # https://jrs-s.net/2018/08/17/zfs-tuning-cheat-sheet/

  # This is optimized for larger files - could use a default recordsize and adjust per dataset
  # sudo zpool create -o ashift=12 -O xattr=sa -O compression=lz4 -O atime=off -O recordsize=1M -O encryption=on -O keyformat=passphrase -O keylocation=file:///run/secrets/zfs-key -m /mnt/zdata zdata /dev/disk/by-id/wwn-0x50014ee2c1b6aed1
  fileSystems."/mnt/zdata" =
    { device = "zdata";
      fsType = "zfs";
    };

  # sudo zfs create zdata/immich
  fileSystems."/var/lib/immich" =
    { device = "zdata/immich";
      fsType = "zfs";
    };

  # sudo zpool create -o ashift=12 -O xattr=sa -O compression=lz4 -O atime=off -O encryption=on -O keyformat=passphrase -O keylocation=file:///run/secrets/zfs-key -m /mnt/zdata zdata /dev/disk/by-id/wwn-0x5002538635c0e312
  fileSystems."/mnt/zssd" =
    { device = "zssd";
      fsType = "zfs";
    };

  # This is optimized for postgresql's 8K page size
  # sudo zfs create -o recordsize=8K zssd/immich
  fileSystems."/var/lib/postgresql" =
    { device = "zssd/postgresql";
      fsType = "zfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
